Feature/register
hyun-Jin-Park-4808/funding pull request #1
Opened 2023-09-21 13:33 UTC by hyun-Jin-Park-4808

### 변경사항

**AS-IS**
회원가입/로그인 api 구현을 하였는데, USER 엔티티에서 권한 설정을 위한 컬럼을 @ElementCollection을 사용해서 작성해줬습니다.
그리고 schema.sql 파일을 통해 db 초기화 세팅을 하였는데, http파일을 통해 회원가입 api 요청을 날렸을 때 500 에러가 납니다.
제 생각에는 role에 대한 컬럼이 user 테이블에 없어서 그런 것 같습니다.
다른 사람들의 블로그를참고했을 때 보통 @ElememtCollection을 사용해 User 테이블을 구성할 때는 따로 테이블에 해당 컬럼 추가를 안 하던데, schema.sql 파일로 초기화를 시켜서 이 부분이 에러가 나는 걸로 예측해봅니다..
schema.sql을 사용 안하고, ddl-auto를 create-drop으로 하면 괜찮을 거 같긴 한데, schema.sql 파일을 사용할 경우에는 이런 상황을 어떻게 해결해야 할 지 감이 잘 안 잡힙니다. 
조언 부탁드립니다.! 
**TO-BE**

### 테스트
 
- [ ] 테스트 코드
- [ ] API 테스트

2023-09-22 09:05 UTC, jaymores requested changes
우선 문제가 발생하면 로그를 확인해 보셔야 합니다. 로컬에 구성후 확인해보면 가장먼저 아래의 로그를 보이네요.

<img width="1111" alt="image" src="https://github.com/hyun-Jin-Park-4808/funding/assets/145752607/ae36b833-59f1-4603-9377-4f63e1cf2ddb">

2023-09-22 09:05 UTC, jaymores commented on src/main/resources/schema.sql
> +CREATE TABLE `USER`
적절한 선언인지 잘 봐주세요.

```sql
CREATE TABLE `USER`
(
    `user_id`       BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 번호',  -- 사용자 번호
    `login_id`      VARCHAR(255) NOT NULL COMMENT '로그인 아이디', -- 로그인 아이디
    `password`      VARCHAR(500)  NOT NULL COMMENT '패스워드',    -- 패스워드 
    `created_date`  DATETIME     NOT NULL COMMENT '가입 날짜',   -- 가입 날짜
    `modified_date` DATETIME     NULL COMMENT '수정 날짜',       -- 수정 날짜
    `removed_date`  DATETIME     NULL COMMENT '탈퇴 날짜'        -- 탈퇴 날짜
)
    COMMENT '사용자';

-- 사용자
-- 제거함
```

2023-09-22 09:05 UTC, jaymores commented on src/main/java/com/hyunjin/funding/domain/User.java
> +  @GeneratedValue(strategy = GenerationType.IDENTITY)
AUTO_INCREMENT 가 설정되어야 Mysql에서 동작합니다.

2023-09-22 09:05 UTC, jaymores commented on src/main/java/com/hyunjin/funding/service/UserService.java
> +    user.setPassword(this.passwordEncoder.encode(user.getPassword())); // 비밀번호 인코딩해서 저장
인코딩된 데이터의 길이가 현재 선언한 SQL 문의 길이에 적합한가요?

2023-09-22 09:20 UTC, jaymores commented
참고로 디버깅 및 개선 후 아래와 같이 요청과 응답을 받아봤습니다.

REQ

```
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "loginId": 999,
  "password": "content",
  "roles": ["a","b"]
}

```

RES

```json
{
  "userId": 1,
  "loginId": "999",
  "password": null,
  "createdDate": "2023-09-22T17:57:58.427298",
  "modifiedDate": null,
  "removedDate": null,
  "roles": [
    "a",
    "b"
  ],
  "enabled": false,
  "accountNonExpired": false,
  "accountNonLocked": false,
  "credentialsNonExpired": false,
  "username": null,
  "authorities": [
    {
      "authority": "a"
    },
    {
      "authority": "b"
    }
  ]
}
```

2023-09-26 07:10 UTC, merged

2023-09-26 12:33 UTC, jaymores reviewed
수고하셨어요. 👍

2023-09-26 12:33 UTC, jaymores commented on src/main/java/com/hyunjin/funding/domain/User.java
> +    return null;
getter 메서드에서 값을 직접 반환하는 구조보단, User 클래스를 참조하는 위치에서 처리하는 것이 Repository 계층의 역할 분리에 더 좋을 것 같네요.

2023-09-26 12:33 UTC, jaymores commented on src/main/java/com/hyunjin/funding/dto/Auth.java
> +  public static class SighIn { // 로그인
특별한 이유가 없는 이상 1파일 1클래스 컨벤션을 지켜주세요. 특히 public은 주의해야해요.

- https://stackoverflow.com/questions/2336692/java-multiple-class-declarations-in-one-file

2023-09-27 12:54 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/hyunjin/funding/domain/User.java
> +    return null;
이 부분은 회원가입 및 로그인 관련 강의를 참고해서 작성했는데 UserDetails를 구현하려면 해당 메서드를 오버라이드해야 한다고 해서 User 엔티티에 작성해야 했습니다!

2023-09-27 12:57 UTC, hyun-Jin-Park-4808 commented on src/main/java/com/hyunjin/funding/dto/Auth.java
> +  public static class SighIn { // 로그인
이 부분도 강의를 참고해서 작성하였는데, 분리를 하는 게 좋을까요??

2023-10-03 11:47 UTC, jaymores commented on src/main/java/com/hyunjin/funding/dto/Auth.java
> +  public static class SighIn { // 로그인
네 분리하는게 좋습니다.